### PR TITLE
Smartctl blog

### PR DESCRIPTION
**Pull request by mfuhrmann**
https://wiki.opennms.org/wiki/Smartctl

https://issues.opennms.org/browse/ORG-74

### CODE REVIEW

**Review by indigo423 — APPROVED** [review]
Fine for me, @JessiDoesStuff can you add some native speaker sprinkles? :)

**Comment by JessiDoesStuff** [comment]
Would be happy to!

But I get this error:

**Comment by indigo423** [comment]
@mfuhrmann can you give JessiDoesStuff the permissions to edit in your repo?

**Comment by mfuhrmann** [comment]
@JessiDoesStuff Done! :-)

**Comment by mfuhrmann** [comment]
@indigo423 Why did you close this one?

**Pull request closed without merging**
