### PR TITLE
IFTTT blog article

### PR DESCRIPTION
**Pull request by mfuhrmann**
@indigo423 
It's not completely done, but a good first draft. Good enough for the fact, that's very late now...
Gnight

### CODE REVIEW

**Review by indigo423 — APPROVED** [review]

**Comment by indigo423** [comment]
@JessiDoesStuff you :metal:

**Comment by mfuhrmann** [comment]
Should we rewrite this article? The initial idea was to write about the lamp itself and why it's the best solution for signaling. But now this article is a mix of "introducing IFTTT support" and "best lamp ever".
The IFTTT article should be definitively published first and the other one can draw on it 1-2 weeks later.

**Comment by indigo423** [comment]
> But now this article is a mix of "introducing IFTTT support" and "best lamp ever".

why rewriting? I don't have a problem with that :)

**Comment by indigo423** [comment]
@mfuhrmann you have mentioned, you would like to have an article more about ways how to get a humans attention. We have several different ways, wallboard, ops board, start page, helm, notifications, etc. I would suggest making a separate article which tackles just this topic.

**Comment by mfuhrmann** [comment]
> why rewriting? I don't have a problem with that :)

To avoid redundancy. Initially I wanted to have the lamp story in the other blog. But the IFTTT blog surely needs an example. 
So the second blog can only focus on the methods and refer to this IFTTT blog. Everything's fine :-)

**Comment by mfuhrmann** [comment]
But... should we change the title? ;-)

**Pull request merged**
